import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `todo.dart` with the code generated by Freezed
part 'todo.freezed.dart';
// optional: Since our ToDo class is serializable, we must add this line.
// But if ToDo was not serializable, we could skip it.
part 'todo.g.dart';

/**
 * To run the code generator, execute the following command:
 * ~~~
 * flutter pub run build_runner build
 * ~~~
 * Or
 * ~~~
 * flutter pub run build_runner build --delete-conflicting-outputs
 * ~~~
 *////

@freezed
class ToDoRecord with _$ToDoRecord {
  factory ToDoRecord(
    int key,
    ToDo value,
  ) = _ToDoRecord;
}

@freezed
class ToDo with _$ToDo {
  factory ToDo({
    /// ToDoのタイトルです
    required String title,

    /// ToDoの完了状態です
    @Default(false) bool archived,
  }) = _ToDo;

  factory ToDo.fromJson(Map<String, dynamic> json) => _$ToDoFromJson(json);
}
/**
 * ToDoRecord = {key:value}
 * value = {"title": title, "archived": true/false}
 *///